site_name: "mkdocs-gen-files"
site_url: "https://oprypin.github.io/mkdocs-gen-files"
repo_url: "https://github.com/oprypin/mkdocs-gen-files"
edit_uri: blob/master/docs/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: teal
    accent: purple

extra_css:
  - assets/style.css

watch:
  - mkdocs_gen_files

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_pages.py
  - literate-nav
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_signature_annotations: true
            show_source: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - def_list
  - toc:
      permalink: "#"

nav:
  - section-index: /mkdocs-section-index/
  - literate-nav: /mkdocs-literate-nav/
  - gen-files:
    - Manual: index.md
    - API: api.md
    - Extras: extras.md
    - Sample: sample/
  - same-dir: /mkdocs-same-dir/
